# Generated by Django 4.1.6 on 2023-02-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('message_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-message_time'],
            },
        ),
    ]
