# Generated by Django 4.1.6 on 2023-02-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_read',
            new_name='is_delivered',
        ),
    ]
