# Generated by Django 4.1.6 on 2023-02-05 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_rename_is_read_message_is_delivered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('room', models.UUIDField(default=uuid.UUID('93f5dad2-76f1-4dfc-a749-1765a723e6b3'))),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_admin', to=settings.AUTH_USER_MODEL)),
                ('member', models.ManyToManyField(related_name='group_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
